# Generated by Django 3.2.5 on 2021-09-16 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bilim',
        ),
    ]
