# Generated by Django 3.2.5 on 2021-09-16 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_bilim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bilim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('foiz', models.CharField(max_length=5)),
                ('cl', models.TextField()),
            ],
        ),
    ]
